// This file is autogenerated by tools/update-file-sizes.js
VIZ.fileSizes = {
  "data/spider.json": 1928,
  "data/station-network.json": 5389,
  "data/station-paths.json": 927,
};
VIZ.fileHashes = {
  "data/spider.json": "8b678242",
  "data/station-network.json": "9511bc5d",
  "data/station-paths.json": "4bc82be2",
};